/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.UsuarioController;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import models.Empleado;
import models.Persona;
import models.Usuario;
import utils.inputValidator;

/**
 *
 * @author JOEL
 */
public class login extends javax.swing.JFrame {

    int xMouse, yMouse;
    boolean isPswVisible = false;

    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/files/images/logo.png")).getImage());
        txusuario.requestFocusInWindow();
        logoerrorusuario.setVisible(false);
        txerrorusuario.setVisible(false);
        logoerrorpsw.setVisible(false);
        txerrorpsw.setVisible(false);
        txpassword_visible.setVisible(false);
    }

    //FUNCIONES
    private void ingreso() {

        if (isPswVisible) {
            txpassword.setText(txpassword_visible.getText());
        }
        
        if (txusuario.getText().trim().isEmpty() || String.valueOf(txpassword.getPassword()).length() < 8) {

            JOptionPane.showMessageDialog(this, "Complete sus credenciales correctamente.");
            if (txusuario.getText().trim().isEmpty()) {
                logoerrorusuario.setVisible(true);
                txerrorusuario.setVisible(true);
                jSeparator1.setBackground(Color.red);
            }
            if (String.valueOf(txpassword.getPassword()).length() < 8) {
                logoerrorpsw.setVisible(true);
                txerrorpsw.setVisible(true);
                jSeparator2.setBackground(Color.red);
            }
        } else {
            UsuarioController usuarioctrl = new UsuarioController();
            Usuario usuario = new Usuario();

            Persona persona = new Persona();
            persona.setDNI(txusuario.getText().trim());

            Empleado empleado = new Empleado();
            empleado.setPersona(persona);

            usuario.setEmpleado(empleado);
            usuario.setPassword(String.valueOf(txpassword.getPassword()).trim());

            if (usuarioctrl.loginUser(usuario)) {
                JOptionPane.showMessageDialog(null, "Login Correcto...");
            } else {
                JOptionPane.showMessageDialog(null, "Usuario y/o contraseña incorrectos...");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        logoerrorusuario = new javax.swing.JLabel();
        txerrorusuario = new javax.swing.JLabel();
        txusuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txerrorpsw = new javax.swing.JLabel();
        logoerrorpsw = new javax.swing.JLabel();
        txpassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        header = new javax.swing.JPanel();
        botoncerrar = new javax.swing.JPanel();
        lbcerrar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botoningresar = new javax.swing.JPanel();
        txingresar = new javax.swing.JLabel();
        btnver_psw = new javax.swing.JToggleButton();
        txpassword_visible = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoerrorusuario.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        logoerrorusuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoerrorusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icons/spam1.png"))); // NOI18N
        background.add(logoerrorusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 204, 36, 36));

        txerrorusuario.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txerrorusuario.setForeground(new java.awt.Color(255, 0, 0));
        txerrorusuario.setText("El usuario es obligatorio");
        background.add(txerrorusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 240, -1, -1));

        txusuario.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txusuario.setForeground(new java.awt.Color(0, 102, 153));
        txusuario.setToolTipText("");
        txusuario.setBorder(null);
        txusuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txusuarioFocusLost(evt);
            }
        });
        txusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txusuarioMousePressed(evt);
            }
        });
        txusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txusuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txusuarioKeyTyped(evt);
            }
        });
        background.add(txusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 204, 348, 36));

        jSeparator1.setBackground(new java.awt.Color(51, 153, 255));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 240, 348, -1));

        txerrorpsw.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txerrorpsw.setForeground(new java.awt.Color(255, 0, 0));
        txerrorpsw.setText("Es obligatorio. Debe tener al menos 8 caracteres. ");
        background.add(txerrorpsw, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 324, -1, -1));

        logoerrorpsw.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        logoerrorpsw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoerrorpsw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icons/spam1.png"))); // NOI18N
        background.add(logoerrorpsw, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 288, 36, 36));

        txpassword.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txpassword.setForeground(new java.awt.Color(0, 102, 153));
        txpassword.setToolTipText("");
        txpassword.setBorder(null);
        txpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txpasswordFocusLost(evt);
            }
        });
        txpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txpasswordMousePressed(evt);
            }
        });
        txpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txpasswordKeyPressed(evt);
            }
        });
        background.add(txpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 288, 312, 36));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Usuario");
        background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 180, 84, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 204));
        jLabel8.setText("INICIO DE SESIÓN");
        background.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 132, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Contraseña");
        background.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 264, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(51, 153, 255));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 324, 348, -1));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        botoncerrar.setBackground(new java.awt.Color(255, 255, 255));
        botoncerrar.setToolTipText("");
        botoncerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botoncerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botoncerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botoncerrarMouseExited(evt);
            }
        });

        lbcerrar.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lbcerrar.setForeground(new java.awt.Color(0, 0, 0));
        lbcerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbcerrar.setText("X");
        lbcerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout botoncerrarLayout = new javax.swing.GroupLayout(botoncerrar);
        botoncerrar.setLayout(botoncerrarLayout);
        botoncerrarLayout.setHorizontalGroup(
            botoncerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
            .addGroup(botoncerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botoncerrarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        botoncerrarLayout.setVerticalGroup(
            botoncerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(botoncerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botoncerrarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbcerrar)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(788, Short.MAX_VALUE)
                .addComponent(botoncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botoncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 864, 36));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/images/favicon.png"))); // NOI18N
        logo.setText("SISTEMA DE RESERVAS");
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 120, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/images/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 168, -1, -1));

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, 420, 492));

        botoningresar.setBackground(new java.awt.Color(0, 134, 190));
        botoningresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botoningresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botoningresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botoningresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botoningresarMouseExited(evt);
            }
        });
        botoningresar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txingresar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txingresar.setForeground(new java.awt.Color(255, 255, 255));
        txingresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txingresar.setText("Ingresar");
        botoningresar.add(txingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 348, 24));

        background.add(botoningresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 372, 348, 36));

        btnver_psw.setBackground(new java.awt.Color(255, 255, 255));
        btnver_psw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icons/ojo-cerrado.png"))); // NOI18N
        btnver_psw.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnver_psw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnver_pswActionPerformed(evt);
            }
        });
        background.add(btnver_psw, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 288, 36, 36));

        txpassword_visible.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txpassword_visible.setForeground(new java.awt.Color(0, 102, 153));
        txpassword_visible.setToolTipText("");
        txpassword_visible.setBorder(null);
        txpassword_visible.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txpassword_visibleFocusLost(evt);
            }
        });
        txpassword_visible.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txpassword_visibleKeyPressed(evt);
            }
        });
        background.add(txpassword_visible, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 288, 312, 36));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txusuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txusuarioFocusLost
        if (txusuario.getText().trim().length() == 0) {
            logoerrorusuario.setVisible(true);
            txerrorusuario.setVisible(true);
            jSeparator1.setBackground(Color.red);
        } else {
            logoerrorusuario.setVisible(false);
            txerrorusuario.setVisible(false);
            jSeparator1.setBackground(new Color(51, 153, 255));
        }
    }//GEN-LAST:event_txusuarioFocusLost

    private void txusuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txusuarioMousePressed
        txusuario.setBorder(BorderFactory.createLineBorder(Color.RED, 0));
        txpassword.setBorder(BorderFactory.createLineBorder(Color.RED, 0));
    }//GEN-LAST:event_txusuarioMousePressed

    private void txusuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txusuarioKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            txpassword.requestFocusInWindow();
        }
    }//GEN-LAST:event_txusuarioKeyPressed

    private void txusuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txusuarioKeyTyped
        inputValidator.Numeros(evt);
    }//GEN-LAST:event_txusuarioKeyTyped

    private void txpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txpasswordFocusLost
        if (String.valueOf(txpassword.getPassword()).length() < 8) {
            logoerrorpsw.setVisible(true);
            txerrorpsw.setVisible(true);
            jSeparator2.setBackground(Color.red);
        } else {
            logoerrorpsw.setVisible(false);
            txerrorpsw.setVisible(false);
            jSeparator2.setBackground(new Color(51, 153, 255));
        }
    }//GEN-LAST:event_txpasswordFocusLost

    private void txpasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txpasswordMousePressed
        txusuario.setBorder(BorderFactory.createLineBorder(Color.RED, 0));
        txpassword.setBorder(BorderFactory.createLineBorder(Color.RED, 0));
    }//GEN-LAST:event_txpasswordMousePressed

    private void txpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txpasswordKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            ingreso();
        }
    }//GEN-LAST:event_txpasswordKeyPressed

    private void botoncerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoncerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_botoncerrarMouseClicked

    private void botoncerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoncerrarMouseEntered
        botoncerrar.setBackground(Color.red);
        lbcerrar.setForeground(Color.white);
    }//GEN-LAST:event_botoncerrarMouseEntered

    private void botoncerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoncerrarMouseExited
        botoncerrar.setBackground(Color.white);
        lbcerrar.setForeground(Color.BLACK);
    }//GEN-LAST:event_botoncerrarMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void botoningresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoningresarMouseClicked
        ingreso();
    }//GEN-LAST:event_botoningresarMouseClicked

    private void botoningresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoningresarMouseEntered
        botoningresar.setBackground(new Color(0, 93, 139));
    }//GEN-LAST:event_botoningresarMouseEntered

    private void botoningresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoningresarMouseExited
        botoningresar.setBackground(new Color(0, 134, 190));
    }//GEN-LAST:event_botoningresarMouseExited

    private void btnver_pswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnver_pswActionPerformed
        // Suponiendo que tienes un JToggleButton llamado toggleButton_ver_clave
        if (btnver_psw.isSelected()) {
            String pass = "";
            char[] passIngresado = txpassword.getPassword();
            for (int i = 0; i < passIngresado.length; i++) {
                pass += passIngresado[i];
            }
            txpassword_visible.setText(pass);
            txpassword_visible.setVisible(true);
            txpassword.setVisible(false);
            isPswVisible = true;

            btnver_psw.setIcon(new ImageIcon(getClass().getResource("/files/icons/ojo-abierto.png")));
        } else {
            String passwordIngresado = txpassword_visible.getText();
            txpassword.setText(passwordIngresado);
            txpassword.setVisible(true);
            txpassword_visible.setVisible(false);
            isPswVisible = false;

            btnver_psw.setIcon(new ImageIcon(getClass().getResource("/files/icons/ojo-cerrado.png")));
        }
    }//GEN-LAST:event_btnver_pswActionPerformed

    private void txpassword_visibleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txpassword_visibleFocusLost
        if (String.valueOf(txpassword_visible.getText()).length() < 8) {
            logoerrorpsw.setVisible(true);
            txerrorpsw.setVisible(true);
            jSeparator2.setBackground(Color.red);
        } else {
            logoerrorpsw.setVisible(false);
            txerrorpsw.setVisible(false);
            jSeparator2.setBackground(new Color(51, 153, 255));
        }
    }//GEN-LAST:event_txpassword_visibleFocusLost

    private void txpassword_visibleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txpassword_visibleKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            ingreso();
        }
    }//GEN-LAST:event_txpassword_visibleKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel botoncerrar;
    private javax.swing.JPanel botoningresar;
    private javax.swing.JToggleButton btnver_psw;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbcerrar;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logoerrorpsw;
    private javax.swing.JLabel logoerrorusuario;
    private javax.swing.JLabel txerrorpsw;
    private javax.swing.JLabel txerrorusuario;
    private javax.swing.JLabel txingresar;
    private javax.swing.JPasswordField txpassword;
    private javax.swing.JTextField txpassword_visible;
    private javax.swing.JTextField txusuario;
    // End of variables declaration//GEN-END:variables
}
